# Generated by Django 4.2.7 on 2023-12-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.DateField(),
        ),
    ]
