# Generated by Django 4.2.7 on 2023-12-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0005_alter_author_born_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.CharField(max_length=50),
        ),
    ]
