# Generated by Django 4.2.7 on 2023-12-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0006_alter_author_born_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quote",
            field=models.TextField(unique=True),
        ),
    ]
