# Generated by Django 4.2.7 on 2023-12-02 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
    ]
